# Generated by Django 4.0.4 on 2022-05-30 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BENHNHAN',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=40, prefix='BN', primary_key=True, serialize=False, verbose_name='ID bệnh nhân')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, verbose_name='Giới tính')),
                ('ngay_sinh', models.DateField(default='01/01/1990', null=True, verbose_name='Ngày sinh')),
                ('dia_chi', models.CharField(max_length=255, null=True, verbose_name='Địa chỉ')),
            ],
        ),
        migrations.CreateModel(
            name='DANHMUC',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=40, prefix='DM', primary_key=True, serialize=False, verbose_name='ID Danh mục')),
                ('ten', models.CharField(max_length=255, verbose_name='Tên')),
                ('loai', models.CharField(choices=[('Bệnh', 'Bệnh'), ('Thuốc', 'Thuốc'), ('Đơn vị', 'Đơn vị'), ('Cách dùng', 'Cách dùng')], max_length=20, verbose_name='Loại')),
                ('gia_tri', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá trị')),
            ],
        ),
        migrations.CreateModel(
            name='PHIEUKHAM',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=40, prefix='PK', primary_key=True, serialize=False, verbose_name='ID phiếu khám')),
                ('ngay_kham', models.DateTimeField(auto_now_add=True, verbose_name='Ngày khám')),
                ('trieu_chung', models.CharField(max_length=100, verbose_name='Triệu chứng')),
                ('id_benhnhan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_core.benhnhan', verbose_name='ID bệnh nhân')),
                ('loai_benh', models.ForeignKey(limit_choices_to={'loai': 'Bệnh'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benh', to='web_core.danhmuc', verbose_name='Loại bệnh')),
            ],
        ),
        migrations.CreateModel(
            name='THAMSO',
            fields=[
                ('loai', models.CharField(choices=[('Tiền khám', 'Tiền khám'), ('Số lượng bệnh nhân tối đa', 'Số lượng bệnh nhân tối đa')], max_length=50, primary_key=True, serialize=False, verbose_name='Loại')),
                ('now_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Hiện tại')),
            ],
        ),
        migrations.CreateModel(
            name='SUDUNGTHUOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('cach_dung', models.ForeignKey(limit_choices_to={'loai': 'Cách dùng'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cach_dung', to='web_core.danhmuc', verbose_name='Cách dùng')),
                ('don_vi', models.ForeignKey(limit_choices_to={'loai': 'Đơn vị'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_vi', to='web_core.danhmuc', verbose_name='Đơn vị')),
                ('id_phieukham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_core.phieukham', verbose_name='ID phiếu khám')),
                ('thuoc', models.ForeignKey(limit_choices_to={'loai': 'Thuốc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='web_core.danhmuc', verbose_name='Thuốc')),
            ],
        ),
    ]
