# Generated by Django 4.0.4 on 2022-05-25 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudungthuoc',
            name='thuoc',
        ),
        migrations.AddField(
            model_name='sudungthuoc',
            name='thuoc',
            field=models.ForeignKey(limit_choices_to={'loai': 'Thuốc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='web_core.danhmuc'),
        ),
    ]
