# Generated by Django 4.0.4 on 2022-05-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieukham',
            name='ngay_kham',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày khám'),
        ),
    ]
