# Generated by Django 4.0.4 on 2022-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0002_alter_phieukham_ngay_kham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieukham',
            name='ngay_kham',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày khám'),
        ),
    ]
