# Generated by Django 4.0.4 on 2022-05-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0002_alter_phieukham_ngay_kham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieukham',
            name='ngay_kham',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày khám'),
        ),
        migrations.AlterField(
            model_name='sudungthuoc',
            name='cach_dung',
            field=models.ForeignKey(limit_choices_to={'loai': 'Cách dùng'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cach_dung', to='web_core.danhmuc', verbose_name='Cách dùng'),
        ),
        migrations.AlterField(
            model_name='sudungthuoc',
            name='don_vi',
            field=models.ForeignKey(limit_choices_to={'loai': 'Đơn vị'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_vi', to='web_core.danhmuc', verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='sudungthuoc',
            name='thuoc',
            field=models.ForeignKey(limit_choices_to={'loai': 'Thuốc'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thuoc', to='web_core.danhmuc', verbose_name='Thuốc'),
        ),
    ]
