# Generated by Django 4.0.4 on 2022-05-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_core', '0002_remove_sudungthuoc_thuoc_sudungthuoc_thuoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieukham',
            name='su_dung_thuoc',
        ),
    ]
